services:
  postgres:
    image: postgres:15.8
    container_name: example-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    command: -p ${POSTGRES_PORT}

elastic:


volumes:
  postgres_data: 